baseURL: https://linsnow.cn/
languageCode: zh-cn
title: L1nSn0w's Site
copyright: Â© 2020-2024 L1nSn0w

# services:
#   googleAnalytics:
#     ID: 

# paginate specifies the maximum number of posts displayed on the home page.
pagination:
  pagerSize: 5
# theme specifies the name of the theme to be used.
theme: xlog
# defaultContentLanguage specifies the default language to use.
defaultContentLanguage: zh-cn
# language.xxx setup
languages:
  zh-cn:
    languageName: cn # will be displayed in the navbar.
    weight: 1
    params:
      greet: :) ä½ å¥½
      status: " å­¦ç‰². SE. GDUTer. "
      description: |
        è¿™é‡Œæ˜¯ [L1nSn0w](/pages/about "å…³äº") çš„ å°å¤©åœ°. æ¬¢è¿ä½ åˆ°æ­¤å¤„é€›ä¸€é€›ï¼å¦‚æœä½ å¯¹[æˆ‘](/pages/resume "ç®€å†")çš„å†…å®¹æ„Ÿå…´è¶£ï¼Œä½ å¯ä»¥åœ¨[å½’æ¡£](/archives "å½’æ¡£")ä¸­æ‰¾åˆ°æˆ‘ä¹‹å‰å†™çš„æ–‡ç« ã€‚
        æˆ‘åœ¨è¿™é‡Œè®°å½•äº†ä¸€äº›æŠ€æœ¯ã€ç”Ÿæ´»ã€å­¦ä¹ ã€å¨±ä¹çš„å†…å®¹.
        è¿™é‡Œä¹Ÿæœ‰æˆ‘çš„ä¸€äº›[æœ‹å‹](/pages/links "å‹é“¾")å’Œæˆ‘æ•æ‰åˆ°çš„ä¸€äº›[ç¬é—´](/pages/gallery "ç”»å»Š"),
        å¸Œæœ›ä½ åœ¨è¿™é‡Œèƒ½æœ‰æ‰€æ”¶è·ï¼Œä¹ŸæœŸå¾…ä½ ç•™ä¸‹è‡ªå·±çš„è¶³è¿¹ï¼Œè®©æˆ‘çŸ¥é“ä½ çš„åˆ°æ¥ã€‚
  
  # en:
  #   languageName: en
  #   weight: 2
  #   params:
  #     status: Student, GDUTer, Crazy. ğŸˆ
  #     description: |
  #       This is `L1nSn0w`'s `Log`. [Me](/pages/about) here records some technology, life, study, and entertainment content.ğŸ¤”
  #       I hope you can find what you want here. ğŸ‘£
  #     greet: :) Hello

params:
  # greet specifies greeting words.
  # greet: Hello :)
  # subtitle speficies a subtitle displayed right after the site title.
  subtitle: 
  # switch specifies two emojis used as the button toggling color themes.
  switch: ["ğŸŒš","ğŸŒ"]
  # minima has one dark theme and multiple light themes. defaultTheme specifies
  # a default light theme to use. currently available options: light, sand, rock, system.
  defaultTheme: light
  # displayDate speficies whether or not to display post date on the home page.
  displayDate: true
  # displayDescription specifies whether or not to display post description on
  # the home page.
  displayDescription: false
  # selectable specifies if or not your post content can be selected.
  selectable: true
  
  author: "L1nSn0w" # author
  description: "ä½ å¥½ï¼Œå­¦ç‰²ï¼Œç‰›é©¬ï¼ŒGDUTerï¼è¿™é‡Œæ˜¯ L1nSn0w çš„ä¸ªäººåšå®¢æ—¥å¿—ã€‚æ¬¢è¿æ¥åˆ°æˆ‘çš„å°å¤©åœ°ï¼Œä½ å¯ä»¥åœ¨è¿™é‡Œæ‰¾åˆ°æˆ‘è®°å½•çš„æŠ€æœ¯ã€ç”Ÿæ´»ã€å­¦ä¹ å’Œå¨±ä¹ç­‰å„ç±»æ–‡ç« ï¼Œè¿˜æœ‰æˆ‘ä¸æœ‹å‹ä»¬æ•æ‰åˆ°çš„ç¾å¥½ç¬é—´ã€‚å¸Œæœ›ä½ èƒ½åœ¨æ­¤å¤„æ”¶è·å¯å‘ï¼Œç•™ä¸‹è¶³è¿¹ï¼" # site description
  keywords: ["L1nSn0w", "ä¸ªäººåšå®¢", "æŠ€æœ¯åˆ†äº«", "ç”Ÿæ´»è®°å½•", "GDUT", "å¨±ä¹", "å­¦ä¹ ", "å‰ç«¯å¼€å‘", "åç«¯å¼€å‘", "Blog", "Log", "Hugo", "Theme"]  # site keywords

  icp: 
    enable: true
    icpurl: https://beian.miit.gov.cn/
    icpinfo: ç²¤ICPå¤‡2023006542

  # social is an array containing as many as social accounts to be displayed  
  # in the buttom of every page.
  social:
    - name: "email"
      url: "mailto:l1nsn0w@qq.com"
    - name: "github"
      url: "https://github.com/lin-snow"
    - name: "rss"
      url: "/index.xml"

  # image in grey style
  filterimg:
    enable: false

  # view-image plugin
  viewimage:
    enable: true

  # math plugin
  math:
    enable: false
    provider: katex

  # diagram plugin
  diagram:
    enable: false
    provider: mermaid

  # comment plugin
  comment:
    enable: true
    provider: twikoo
    # check out https://twikoo.js.org/
    twikoo:
      envId: https://comment.linsnow.cn
      region: ap-guangzhou # ç¯å¢ƒåœ°åŸŸï¼Œé»˜è®¤ä¸º ap-shanghaiï¼Œè…¾è®¯äº‘ç¯å¢ƒå¡« ap-shanghai æˆ– ap-guangzhouï¼›Vercel ç¯å¢ƒä¸å¡«
      lang: zh-CN # ç”¨äºæ‰‹åŠ¨è®¾å®šè¯„è®ºåŒºè¯­è¨€ï¼Œæ”¯æŒçš„è¯­è¨€åˆ—è¡¨ https://github.com/twikoojs/twikoo/blob/main/src/client/utils/i18n/index.js
    # check out https://artalk.js.org/
    artalk:
      server: https://artalk.linsnow.cn
      site: L1nSn0w's Log
    # check out https://waline.js.org/
    waline:
      serverURL: 
      placeholder: è¯´ç‚¹ä»€ä¹ˆå§...
      # check out https://valine.js.org
    # check out https://disqus.com/
    disqus:
      shortname: hugo-minima
      # check out https://utteranc.es
    utterances:
      repo: mivinci/hugo-theme-minima
      issueTerm: pathname
      label: comment
    # check out https://giscus.app
    giscus: 
      repo: mivinci/hugo-theme-minima
      repoId: MDEwOlJlcG9zaXRvcnkzODcxMjM2NDU=
      category: Comments
      categoryId: DIC_kwDOFxMJvc4CScQm
      mapping: pathname
      inputPosition: buttom # bottom | top
      reactions: true
      metadata: false
    

  # search plugin
  search:
    enable: true
    provider: fuse
    title: Search
    placeholder: Enter keywords
    # check out https://fusejs.io
    fuse:
      keys:
        - title
        - permalink
        - summary
        - content
      distance: 100
      location: 0
      threshold: 0.6
      ignoreLocation: false
      isCaseSensitive: false
      includeScore: false
      includeMatches: ture
      minMatchCharLength: 1
      shouldSort: true
      findAllMatches: true

  # éœé¹œæ–‡æ¥·å­—ä½“
  font_cleanwhite:
    enable: true
    cdn: /font/result.css # /font/LXGWWenKaiScreen/result.css # https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css # <!-- Screen version -->


# menu.main is an array containing what is used as the navigator.
menu:
  main:
    - identifier: /
      name: home
      weight: 1
    # - identifier: tags
    #   name: tags
    #   weight: 2
    - identifier: series
      name: series
      weight: 3
    - identifier: search
      name: search
      weight: 4


# taxonomies defines ways to classify yout posts. Below are some presets that
# most bloggers use, so you can replace them with whatever you like.
taxonomies:
  category: categories
  tag: tags
  series: series

# outputs tells Hugo the kind of files to be rendered.
outputs:
  home:
    - HTML
    - RSS
    - JSON

# markup.highlight has two keys set to make sure that the syntax highlighting
# in your posts are rendered correctly, so DO NOT edit them.
markup:
  highlight:
    lineNos: false
    noClasses: false
  goldmark:
    renderer:
        unsafe: true
    renderHooks:
      image:
        enableDefault: true
      parser:
        wrapStandAloneImageWithinParagraph: false
